<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="BoemTest" nsURI="http://fr.ibp.odv/BoemTest" nsPrefix="BoemTest">
  <eClassifiers xsi:type="ecore:EClass" name="A" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="childrenNodeA" upperBound="-1"
        eType="#//Node" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="childrenNode2A" upperBound="-1"
        eType="#//Node" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="childNodeA" eType="#//Node"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referencesNodeA" upperBound="-1"
        eType="#//Node"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referenceNodeA" eType="#//Node"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="autoContainementA" upperBound="-1"
        eType="#//A" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="B" eSuperTypes="#//A">
    <eStructuralFeatures xsi:type="ecore:EReference" name="childrenNodeB" upperBound="-1"
        eType="#//Node" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="childNodeB" eType="#//Node"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="enumAttr" eType="#//AnEnumeration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="childrenNodeBNode" eType="#//BNode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="C" eSuperTypes="#//B">
    <eStructuralFeatures xsi:type="ecore:EReference" name="childrenNodeC" upperBound="-1"
        eType="#//Node" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="childNodeC" eType="#//Node"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referencesNodeC" upperBound="-1"
        eType="#//Node"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referenceNodeC" eType="#//Node"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Node" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//Node" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AnEnumeration">
    <eLiterals name="LITERAL0"/>
    <eLiterals name="LITERAL1" value="1"/>
    <eLiterals name="LITERAL2" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
